Добавлены данные со Students.LastPayment
xx3u/amal_frontend pull request #112
Opened 2021-07-27 14:32 UTC by xx3u

#102 

Добавлены данные со Students.LastPayment

Время выполнения: 2 часа

2021-07-28 13:28 UTC, OmegonAlpharius commented on src/containers/PaymentsContainer/PaymentsContainer.js
> +  });
map здесь не подходит
```suggestion

 const lastPayments = [];
  students.forEach((student) => {
    if (student.LastPayment[0]) {
      lastPayments.push({
        id: student.LastPayment[0].id,
        student: `${student.firstName} ${student.lastName}`,
        date: student.LastPayment[0].date,
        amount: student.LastPayment[0].amount,
        status: student.LastPayment[0].status ? 'Оплачено' : 'Неоплачено',
        comment: student.LastPayment[0].comment,
        studentId: student.id,
      });
    }
  });
```

2021-07-28 13:41 UTC, xx3u commented on src/containers/PaymentsContainer/PaymentsContainer.js
> +  });
исправлено

2021-07-28 15:14 UTC, OmegonAlpharius approved these changes

2021-07-29 05:28 UTC, BauyrjanSeidahmet requested changes

2021-07-29 05:28 UTC, BauyrjanSeidahmet commented on src/components/PaymetsTable/PaymentsTable.js
>          return format(new Date(row.date), 'MM/dd/yyyy');
Написали американский формат даты, поменяй пожалуйста на привычный для нас формат: день.месяц.год 
```suggestion
        return format(new Date(row.date), 'dd.MM.yyyy');
```

2021-07-29 06:41 UTC, xx3u commented on src/components/PaymetsTable/PaymentsTable.js
>          return format(new Date(row.date), 'MM/dd/yyyy');
Такой формат применен везде для консистентности отображения даты. 
Если поменять здесь, то надо поменять в формах. Но в формах нельзя поменять, т.к. material-ui выдает ошибку: The specified value "29.07.2021" does not conform to the required format, "yyyy-MM-dd".

![image](https://user-images.githubusercontent.com/45433350/127444092-df9b73c6-5f0e-4d9e-b655-6f3d50f6e5f3.png)

2021-07-29 06:44 UTC, BauyrjanSeidahmet approved these changes

2021-07-29 06:44 UTC, merged