Feature group lessons page
xx3u/amal_frontend pull request #128
Opened 2021-08-02 17:03 UTC by BauyrjanSeidahmet

#125 
Создана страница уроков
Дата: 02.08.2021
Время: 7 часов

2021-08-02 19:25 UTC, xx3u requested changes

2021-08-02 19:25 UTC, xx3u commented on src/containers/LessonsContainer/LessonsContainer.js
> +      isInitialMount.current = false;
1) для чего используется это условие? isInitialMount всегда false
2) чем отличается isInitialMount от без него
```
  useEffect(() => {
    dispatch(getTeachersBySubject(lesson.subjectId));
  }, [lesson]);
```
3) надо поставить условие  lesson.subjectId &&  впереди dispatch, если внутри, то когда нажимаешь на X в выборе Предмета,  то появляется ошибка 
![image](https://user-images.githubusercontent.com/45433350/127911634-c6a14f2e-06be-41b3-b323-e44ce153d410.png)

```suggestion
  useEffect(() => {
    lesson.subjectId && dispatch(getTeachersBySubject(lesson.subjectId));
  }, [lesson]);
```

2021-08-02 19:25 UTC, xx3u commented on src/containers/LessonsContainer/LessonsContainer.js
> +          onChange={(event, value) => setGroup(value)}
мы разве используем name, value?
```suggestion
onChange={(e, value) => setLesson({ ...lesson, groupId: value?.id })}
```

2021-08-02 19:25 UTC, xx3u commented on src/containers/LessonsContainer/LessonsContainer.js
> +          onChange={(event, value) => setSubject(value)}
```suggestion
onChange={(e, value) => setLesson({ ...lesson, subjectId: value?.id })}
```

2021-08-02 19:25 UTC, xx3u commented on src/containers/LessonsContainer/LessonsContainer.js
> +          onChange={(event, value) => setTeacher(value)}
```suggestion
getOptionSelected={(option) => `${option.firstName} ${option.lastName}`}
onChange={(e, value) => setLesson({ ...lesson, teacherId: value?.id })}
```

2021-08-02 19:25 UTC, xx3u commented on src/helpers/helpers.js
> +  const firstday = new Date(date.setDate(first)).toUTCString();
зачем мы превращаем в toUTCString()?

2021-08-02 19:25 UTC, xx3u commented on src/containers/LessonsContainer/LessonsContainer.js
> +  const [selectedDate, setSelectedDate] = useState(new Date());
Зачем нам сохранять целые объекты со всеми значениями отдельно по group, subject... нам же нужны только их id, т.е. из всего объекта group только groupId.
Почему нам не сделать один объект и сохранять только те значения, которые нам нужны
```suggestion
const [lesson, setLesson] = useState({
    groupId: '',
    subjectId: '',
    teacherId: '',
  });
```
Также потом через setLesson добавлять нужные переменные в один стейт.

2021-08-02 19:25 UTC, xx3u commented on src/containers/LessonsContainer/LessonsContainer.js
> +  getWeekdates(copySelectedDate);
Функция getWeekdates показывает текущее время. Предполагаю, что надо также изменить время старта на начало занятий и время последнего дня на конец занятий.
![image](https://user-images.githubusercontent.com/45433350/127912160-8b92ce3e-d007-4104-b2d1-da8e61757bf6.png)

2021-08-02 19:25 UTC, xx3u commented on src/helpers/helpers.js
> +    lastday,
на бэке в модели поля называются startTime, endTime

2021-08-02 19:25 UTC, xx3u commented on src/store/actions/teachersActions.js
> +      const resp = await axios.get('/teachers?subjectId=' + id);
```suggestion
      const resp = await axios.get(`/teachers?subjectId=${id}`);
```

2021-08-02 19:25 UTC, xx3u commented on src/store/actions/teachersActions.js
> +
нет action на request

2021-08-03 03:47 UTC, xx3u commented on src/containers/LessonsContainer/LessonsContainer.js
> +  const [selectedDate, setSelectedDate] = useState(new Date());
Надо еще значение дат добавить

2021-08-03 07:34 UTC, BauyrjanSeidahmet commented on src/containers/LessonsContainer/LessonsContainer.js
> +      isInitialMount.current = false;
initialMount и это условие выполняется чтобы, этот юзефект не вызывался при рендере, а только вызовался только при изменении lesson. Убрал усовие и написал subjectId && перед dispatch.

2021-08-03 07:35 UTC, BauyrjanSeidahmet commented on src/containers/LessonsContainer/LessonsContainer.js
> +          onChange={(event, value) => setGroup(value)}
убрал

2021-08-03 07:40 UTC, BauyrjanSeidahmet commented on src/store/actions/teachersActions.js
> +
request не нужен, у нас не будет loading при получении учителей по предметам и отбражении их в Autocomplete.

2021-08-03 13:05 UTC, BauyrjanSeidahmet commented on src/helpers/helpers.js
> +    lastday,
изменил

2021-08-03 13:06 UTC, BauyrjanSeidahmet commented on src/containers/LessonsContainer/LessonsContainer.js
> +  const [selectedDate, setSelectedDate] = useState(new Date());
исправил

2021-08-03 13:07 UTC, BauyrjanSeidahmet commented on src/helpers/helpers.js
> +  const firstday = new Date(date.setDate(first)).toUTCString();
для того чтобы получить стринговые данные

2021-08-03 13:07 UTC, BauyrjanSeidahmet commented on src/containers/LessonsContainer/LessonsContainer.js
> +          onChange={(event, value) => setTeacher(value)}
убрал

2021-08-03 13:07 UTC, BauyrjanSeidahmet commented on src/containers/LessonsContainer/LessonsContainer.js
> +          onChange={(event, value) => setSubject(value)}
убрал

2021-08-03 13:36 UTC, BauyrjanSeidahmet commented on src/containers/LessonsContainer/LessonsContainer.js
> +  getWeekdates(copySelectedDate);
время занятия статичное

2021-08-03 14:07 UTC, xx3u approved these changes

2021-08-03 14:42 UTC, BauyrjanSeidahmet commented on src/store/actions/teachersActions.js
> +      const resp = await axios.get('/teachers?subjectId=' + id);
изменил

2021-08-03 14:49 UTC, ZaurQoban approved these changes

2021-08-03 14:53 UTC, merged