Отображение, создание уроков
xx3u/amal_frontend pull request #129
Opened 2021-08-05 09:38 UTC by nurlan212

#124 

Создать таблицу отображающую групповые занятия. Реализвать создание уроков по клику по ячейкам таблицы.

Выполнено: 05.08.2021 / Срок сдачи: 04.08.2021

2021-08-05 13:21 UTC, xx3u requested changes

2021-08-05 13:21 UTC, xx3u commented on src/containers/LessonsContainer/LessonsContainer.js
> +    });
надо обновить функцию в helpers getWeekdates чтобы она отображала время. т.к. необходимо время правильное передавать для отображения всех уроков за неделю

2021-08-05 13:21 UTC, xx3u commented on src/containers/LessonsContainer/LessonsContainer.js
> +    };
зачем мы создаем newLesson если у нас есть lesson с теми же параметрами?

2021-08-05 13:21 UTC, xx3u commented on src/components/ScheduleTable/ScheduleTable.js
> +  }, [selectedParams]);
при изменении параметров обнуляется вся таблица с имеющимся расписанием уроков
```suggestion
  }, [selectedParams.startTime, selectedParams.groupId]);
```

2021-08-05 13:21 UTC, xx3u commented on src/store/actions/lessonsAction.js
> +      const response = await axios.get(`/lessons?groupId=${groupId}&startTime=${startTime}&endTime=${endTime}`);
обновить endpoint
```suggestion
      const response = await axios.get(`/groups/${groupId}/lessons?startTime=${startTime}&endTime=${endTime}`);
```

2021-08-05 13:21 UTC, xx3u commented on src/containers/LessonsContainer/LessonsContainer.js
>    }, [lesson.subjectId]);
@BauyrjanSeidahmet перепроверить dispatch по учителям, при изменении предмета в списке остается старый учитель

2021-08-05 13:21 UTC, xx3u commented on src/components/ScheduleTable/ScheduleTable.js
> +  });
может это обернуть в функцию, которая принимает параметры для startTime, endTime и переиспользовать во время setWeekLessons?

2021-08-05 13:21 UTC, xx3u commented on src/components/ScheduleTable/ScheduleTable.js
> +      return copyLessons;
использовать оберточную функцию в строках 15~25 для передачи startTime, endTime

2021-08-05 13:21 UTC, xx3u commented on src/components/ScheduleTable/CustomCard/CustomCard.js
> +import CardActions from '@material-ui/core/CardActions';
убрать неиспользуемые элементы
![image](https://user-images.githubusercontent.com/45433350/128348723-266b82de-9b49-4ec3-a692-8f78d76ef4b6.png)

2021-08-05 13:21 UTC, xx3u commented on src/components/ScheduleTable/CustomCard/CustomCard.js
> +import Button from '@material-ui/core/Button';
убрать неиспользуемые элементы

2021-08-05 13:21 UTC, xx3u commented on src/components/ScheduleTable/CustomCard/CustomCard.js
> +const CustomCard = ({ id = '', subject = '', teacher = '', onClickHandler, startTime, endTime }) => {
- убрать неиспользуемые элементы id
- почему мы используем string?

2021-08-05 13:21 UTC, xx3u commented on src/components/ScheduleTable/ScheduleTable.js
> +          });
попробовать эту лапшу превратить в функцию с циклом. здесь берется lessonWeekDay, если 1, то значение mon меняется, если 2, то значение tue, типа тоже 2.

2021-08-07 13:39 UTC, nurlan212 commented on src/containers/LessonsContainer/LessonsContainer.js
> +    });
сделан

2021-08-07 13:43 UTC, nurlan212 commented on src/components/ScheduleTable/ScheduleTable.js
> +  }, [selectedParams]);
исправлен

2021-08-07 13:44 UTC, nurlan212 commented on src/store/actions/lessonsAction.js
> +      const response = await axios.get(`/lessons?groupId=${groupId}&startTime=${startTime}&endTime=${endTime}`);
исправлен

2021-08-07 13:45 UTC, nurlan212 commented on src/containers/LessonsContainer/LessonsContainer.js
>    }, [lesson.subjectId]);
Бауыржану передам

2021-08-07 13:45 UTC, nurlan212 commented on src/components/ScheduleTable/ScheduleTable.js
> +      return copyLessons;
сделан

2021-08-07 13:48 UTC, nurlan212 commented on src/components/ScheduleTable/CustomCard/CustomCard.js
> +import CardActions from '@material-ui/core/CardActions';
исправлен

2021-08-07 13:49 UTC, nurlan212 commented on src/components/ScheduleTable/CustomCard/CustomCard.js
> +import Button from '@material-ui/core/Button';
исправлен

2021-08-07 13:50 UTC, nurlan212 commented on src/components/ScheduleTable/CustomCard/CustomCard.js
> +const CustomCard = ({ id = '', subject = '', teacher = '', onClickHandler, startTime, endTime }) => {
убрал id, subject, teacher по умолчанию передал как значение пустую строку.

2021-08-07 13:50 UTC, nurlan212 commented on src/components/ScheduleTable/ScheduleTable.js
> +          });
исправлен

2021-08-09 15:35 UTC, OmegonAlpharius requested changes

2021-08-09 15:35 UTC, OmegonAlpharius commented on src/components/ScheduleTable/CustomCard/CustomCard.js
> +  },
Не используется
```suggestion

```

2021-08-09 15:35 UTC, OmegonAlpharius commented on src/components/ScheduleTable/CustomCard/CustomCard.js
> +      }}
Поднять callback в компонент выше, тогда компонент чище будет
```suggestion
      onClick={onClickHandler}
```

2021-08-09 15:35 UTC, OmegonAlpharius commented on src/components/ScheduleTable/CustomCard/CustomCard.js
> +const CustomCard = ({ subject = '', teacher = '', onClickHandler, startTime, endTime }) => {
Если callback поднять выше эти props здесь не нужны
```suggestion
const CustomCard = ({ subject = '', teacher = '', onClickHandler }) => {
```

2021-08-09 15:35 UTC, OmegonAlpharius commented on src/components/ScheduleTable/TableWithCard/TableWithCard.js
> +                            endTime={row[col.field].endTime}
Лишние пропсы зачем передавать, и CustomCard будет чище
```suggestion
  onClickHandler={() => {
                              return onClickHandler(row[col.field].startTime, row[col.field].startTime);
                            }}
```

2021-08-09 15:35 UTC, OmegonAlpharius commented on src/components/ScheduleTable/TableWithCard/TableWithCard.js
> +                  {columns.map((col) => {
Так можно избавиться от col. в коде ниже
```suggestion
                  {columns.map(({field}) => {
```

2021-08-09 15:35 UTC, OmegonAlpharius commented on src/pages/LessonsPage/LessonsPage.js
> +    // paddingRight: 700,
```suggestion

```

2021-08-09 15:35 UTC, OmegonAlpharius commented on src/pages/LessonsPage/LessonsPage.js
> +      {/* <ScheduleTable /> */}
```suggestion
   
```

2021-08-09 15:35 UTC, OmegonAlpharius commented on src/store/actions/lessonsAction.js
> +        `/groups/${groupId}/lessons?groupId=${groupId}&startTime=${startTime}&endTime=${endTime}`
```suggestion
        `/groups/${groupId}/lessons?startTime=${startTime}&endTime=${endTime}`
```

2021-08-09 15:35 UTC, OmegonAlpharius commented on src/helpers/addDays.js
> +};
Использовать библиотеку date-fns  https://date-fns.org/docs/Getting-Started

2021-08-09 15:35 UTC, OmegonAlpharius commented on src/helpers/getDateISOString.js
> +};
Использовать библиотеку date-fns  https://date-fns.org/docs/Getting-Started

2021-08-09 15:35 UTC, OmegonAlpharius commented on src/helpers/getDateWithTime.js
> +};
Использовать библиотеку date-fns  https://date-fns.org/docs/Getting-Started

2021-08-09 15:35 UTC, OmegonAlpharius commented on src/helpers/getTimeStringInDoubleFigures.js
> +};
Использовать библиотеку date-fns  https://date-fns.org/docs/Getting-Started

2021-08-09 15:35 UTC, OmegonAlpharius commented on src/helpers/helpers.js
>      firstday,
Использовать библиотеку date-fns  https://date-fns.org/docs/Getting-Started

2021-08-09 17:52 UTC, nurlan212 commented on src/components/ScheduleTable/CustomCard/CustomCard.js
> +      }}
исправлен

2021-08-09 17:52 UTC, nurlan212 commented on src/components/ScheduleTable/CustomCard/CustomCard.js
> +const CustomCard = ({ subject = '', teacher = '', onClickHandler, startTime, endTime }) => {
исправлен

2021-08-09 17:52 UTC, nurlan212 commented on src/components/ScheduleTable/TableWithCard/TableWithCard.js
> +                            endTime={row[col.field].endTime}
исправлен

2021-08-09 17:52 UTC, nurlan212 commented on src/components/ScheduleTable/TableWithCard/TableWithCard.js
> +                  {columns.map((col) => {
исправлен

2021-08-09 17:55 UTC, nurlan212 commented on src/pages/LessonsPage/LessonsPage.js
> +    // paddingRight: 700,
исправлен

2021-08-09 17:55 UTC, nurlan212 commented on src/pages/LessonsPage/LessonsPage.js
> +      {/* <ScheduleTable /> */}
исправлен

2021-08-09 17:55 UTC, nurlan212 commented on src/store/actions/lessonsAction.js
> +        `/groups/${groupId}/lessons?groupId=${groupId}&startTime=${startTime}&endTime=${endTime}`
исправлен

2021-08-09 18:48 UTC, xx3u approved these changes

2021-08-11 08:09 UTC, OmegonAlpharius commented on src/pages/LessonsPage/LessonsPage.js
> +// import ScheduleTable from '../../components/ScheduleTable/ScheduleTable';
```suggestion

```

2021-08-11 08:09 UTC, OmegonAlpharius commented on src/pages/LessonsPage/LessonsPage.js
> +  lessonsPage: {},
```suggestion

```

2021-08-11 09:40 UTC, nurlan212 commented on src/pages/LessonsPage/LessonsPage.js
> +// import ScheduleTable from '../../components/ScheduleTable/ScheduleTable';
исправлен

2021-08-11 09:40 UTC, nurlan212 commented on src/pages/LessonsPage/LessonsPage.js
> +  lessonsPage: {},
исправлен

2021-08-11 14:13 UTC, OmegonAlpharius approved these changes

2021-08-11 14:13 UTC, merged