Feature error alert
xx3u/amal_frontend pull request #136
Opened 2021-08-10 13:50 UTC by ZaurQoban

Указать номер тикета
#79 

Краткое описание задачи
Найти способ отображения сетевых ошибок на фронте.

Задействована библиотека react-notifications. К экшенам с апи-запросами добавлен NotificationManager на ошибку. 
Для гет-запросов пока используется тайтл "Fetch error", post - "Post error" и др.

Выполнено: 10.08.21 / Срок сдачи: 10.08.21

Затрачено в общем 8 часов (с учетом изучения разных материалов и попытки реализации разных методик, проб и ошибок, перед переходом на указанную библиотеку).

2021-08-11 16:07 UTC, OmegonAlpharius requested changes
Нужно спулить обновления с dev ветки

2021-08-12 08:29 UTC, ZaurQoban commented
@OmegonAlpharius 
Спуллил и сохранил

2021-08-14 13:33 UTC, xx3u reviewed
- Сейчас отображение такой ошибки ничего не говорит пользователю

![image](https://user-images.githubusercontent.com/45433350/129447905-0096c618-0143-4d2f-a6d6-6804ef1e8dde.png)

2021-08-29 04:27 UTC, xx3u commented on src/pages/PaymentsPage/PaymentsPage.js
> +import { useSelector } from 'react-redux';
не применяется

2021-08-29 04:27 UTC, xx3u commented on src/store/actions/groupsAction.js
> +      dispatch(addNewGroupFailure(error.response));
не добавляем NotificationManager?

2021-08-29 04:27 UTC, xx3u commented on src/store/actions/groupsAction.js
> +      dispatch(addNewGroupFailure(error));
не добавляем NotificationManager?

2021-08-29 04:27 UTC, xx3u commented on src/store/actions/studentsAction.js
> +      dispatch(addNewStudentFailure(error.response));
не добавляем NotificationManager?

2021-08-29 04:27 UTC, xx3u commented on src/store/actions/studentsAction.js
> +      dispatch(addNewStudentFailure(error));
не добавляем NotificationManager?

2021-08-29 04:27 UTC, xx3u commented on src/store/actions/studentsAction.js
> +      dispatch(updateStudentFailure(error));
не добавляем NotificationManager?

2021-08-29 04:27 UTC, xx3u commented on src/store/actions/studentsAction.js
> +      dispatch(updateStudentFailure(error));
не добавляем NotificationManager?

2021-08-29 04:27 UTC, xx3u commented on src/store/actions/teachersActions.js
> +        dispatch(addTeacherFailure(error.response));
не добавляем NotificationManager?

2021-08-29 04:27 UTC, xx3u commented on src/store/actions/teachersActions.js
> +        dispatch(editTeacherFailure(error.response));
не добавляем NotificationManager?

2021-08-29 05:12 UTC, ZaurQoban commented on src/pages/PaymentsPage/PaymentsPage.js
> +import { useSelector } from 'react-redux';
@xx3u 
Убрал

2021-08-29 05:13 UTC, ZaurQoban commented on src/store/actions/groupsAction.js
> +      dispatch(addNewGroupFailure(error.response));
@xx3u 
Я полагал, что там, где алерт в формах, нотификатор убирается, нет?

2021-08-29 05:15 UTC, ZaurQoban commented on src/store/actions/studentsAction.js
> +      dispatch(addNewStudentFailure(error.response));
@xx3u  Здесь по аналогии с группами - алерт в стационарной форме. Говорили же, что он должен заменить нотификатор.

2021-08-29 05:18 UTC, ZaurQoban commented on src/store/actions/teachersActions.js
> +        dispatch(editTeacherFailure(error.response));
@xx3u по аналогии с группами\студентами. Или, все-таки, вернуть?

2021-08-29 05:36 UTC, xx3u approved these changes

2021-08-29 13:35 UTC, OmegonAlpharius reviewed
При создании предмета падает приложение
https://i.imgur.com/ZolaEMx.png

2021-08-29 13:47 UTC, OmegonAlpharius reviewed
Если  попробовать добавить ученика с некорректным email появится ошибка, без текста
https://i.imgur.com/26gHg0T.png

2021-08-30 15:19 UTC, nurlan212 approved these changes

2021-08-30 15:33 UTC, OmegonAlpharius approved these changes

2021-08-30 15:37 UTC, merged