Создание уроков на период
xx3u/amal_frontend pull request #137
Opened 2021-08-10 19:14 UTC by xx3u

#132 

Создание уроков на период

Время выполнения: 3 часа

2021-08-11 15:52 UTC, OmegonAlpharius requested changes

2021-08-11 15:52 UTC, OmegonAlpharius commented on src/containers/Forms/Lesson/CreateLessons.js
> +import { registerLocale } from 'react-datepicker';
Нет пакета в  package.json
```suggestion
import { registerLocale } from 'react-datepicker';
```

2021-08-11 15:52 UTC, OmegonAlpharius commented on src/containers/Forms/Lesson/CreateLessons.js
> +  registerLocale('ru', ru);
Не пойму где используется

2021-08-11 15:52 UTC, OmegonAlpharius commented on src/containers/Forms/Lesson/CreateLessons.js
> +              id='date-picker-inline'
id повторяется

2021-08-11 15:52 UTC, OmegonAlpharius commented on src/containers/Forms/Lesson/CreateLessons.js
> +              format='MM/dd/yyyy'
Формат чтобы был не американский
```suggestion
            format='dd MMM yyyy'
```

2021-08-11 15:52 UTC, OmegonAlpharius commented on src/containers/Forms/Lesson/CreateLessons.js
> +              format='MM/dd/yyyy'
```suggestion
            format='dd MMM yyyy'
```

2021-08-11 15:52 UTC, OmegonAlpharius commented on src/containers/LessonsContainer/LessonsContainer.js
> +          </Button>
Добавить disable если нет группы

2021-08-11 16:30 UTC, xx3u commented on src/containers/Forms/Lesson/CreateLessons.js
> +import { registerLocale } from 'react-datepicker';
добавлен

2021-08-11 16:31 UTC, xx3u commented on src/containers/Forms/Lesson/CreateLessons.js
> +  registerLocale('ru', ru);
без метода не признает локализацию
![image](https://user-images.githubusercontent.com/45433350/129067553-567b8d3e-84e7-4bab-8ecb-2071fadbd166.png)

2021-08-11 16:33 UTC, xx3u commented on src/containers/Forms/Lesson/CreateLessons.js
> +              id='date-picker-inline'
изменены

2021-08-11 16:34 UTC, xx3u commented on src/containers/Forms/Lesson/CreateLessons.js
> +              format='MM/dd/yyyy'
изменено

2021-08-11 16:34 UTC, xx3u commented on src/containers/Forms/Lesson/CreateLessons.js
> +              format='MM/dd/yyyy'
принято

2021-08-11 16:41 UTC, xx3u commented on src/containers/LessonsContainer/LessonsContainer.js
> +          </Button>
ок, добавлено

2021-08-11 17:08 UTC, OmegonAlpharius requested changes

2021-08-11 17:08 UTC, OmegonAlpharius commented on src/containers/Forms/Lesson/CreateLessons.js
> +import { registerLocale } from 'react-datepicker';
Что дает эта утилита, я ее убрал и все так же работает?

2021-08-11 17:08 UTC, OmegonAlpharius commented on src/containers/LessonsContainer/LessonsContainer.js
> +          <Button variant='contained' onClick={(e) => openPaymentForm(e)} disabled={lesson.groupId  === '' || lesson.groupId === undefined}>
```suggestion
          <Button variant='contained' onClick={(e) => openPaymentForm(e)} disabled={!lesson.groupId}>
```

2021-08-11 17:08 UTC, OmegonAlpharius commented on src/containers/Forms/Lesson/CreateLessons.js
> +import { registerLocale } from 'react-datepicker';
Мне кажется этот пакет лишний

Убрала

2021-08-11 17:08 UTC, OmegonAlpharius commented on src/containers/Forms/Lesson/CreateLessons.js
> +  registerLocale('ru', ru);
Без этого  (registerLocale('ru', ru);) все отлично работает

Снесла

2021-08-11 17:55 UTC, nurlan212 reviewed
При ошибке когда создаем уроков на период, не будем менять стэт? например хотяб loading=false

2021-08-11 17:55 UTC, nurlan212 commented on src/store/reducers/lessonsReducer.js
> +    case CREATE_LESSONS_FAILURE:
```suggestion
    case CREATE_LESSONS_FAILURE:
```
стэйт не будет менять при ошибке?

2021-08-11 18:49 UTC, xx3u commented on src/containers/LessonsContainer/LessonsContainer.js
> +          <Button variant='contained' onClick={(e) => openPaymentForm(e)} disabled={lesson.groupId  === '' || lesson.groupId === undefined}>
если поле Группа пустое, или на Х нажали и очистили, то кнопка по Созданию становится доступной. Поэтому условия являются не лишними.

2021-08-11 18:55 UTC, xx3u commented on src/store/reducers/lessonsReducer.js
> +    case CREATE_LESSONS_FAILURE:
исправлено

2021-08-12 02:31 UTC, nurlan212 approved these changes

2021-08-12 08:28 UTC, OmegonAlpharius commented on src/containers/Forms/Lesson/CreateLessons.js
> +import { MuiPickersUtilsProvider, KeyboardDatePicker } from '@material-ui/pickers';
Нужно для локализации
```suggestion
import { ru } from 'date-fns/locale';
import { MuiPickersUtilsProvider, KeyboardDatePicker } from '@material-ui/pickers';
```

2021-08-12 08:28 UTC, OmegonAlpharius commented on src/containers/Forms/Lesson/CreateLessons.js
> +        <MuiPickersUtilsProvider utils={DateFnsUtils}>
И здесь для локализации
```suggestion
        <MuiPickersUtilsProvider locale={ru} utils={DateFnsUtils}>
```

2021-08-12 08:28 UTC, OmegonAlpharius commented on src/containers/LessonsContainer/LessonsContainer.js
> +            disabled={lesson.groupId  === '' || lesson.groupId === undefined}
Вроде оставлял уже коммент, там не заметила наверно здесь преобразование в bool с инверсией
```suggestion
            disabled={!lesson.groupId}
```

2021-08-12 09:35 UTC, OmegonAlpharius approved these changes

2021-08-12 09:36 UTC, merged