Feature add stream
xx3u/amal_frontend pull request #204
Opened 2021-09-11 13:44 UTC by ZaurQoban

Указать номер тикета

Краткое описание задачи
Добавлена возможность создания потоков, форма интегрирована в страницу добавления студентов

Выполнено: дата / Срок сдачи: дата
11.09.21

2021-09-11 14:12 UTC, OmegonAlpharius requested changes

2021-09-11 14:12 UTC, OmegonAlpharius commented on src/store/actions/streamsAction.js
> +      NotificationManager.error(error.response.data, 'Post error!', 5000);
Тоже на русском нужно
```suggestion
      NotificationManager.error(error.response.data, 'Ошибка отправки данных!', 5000);
```

2021-09-11 14:12 UTC, OmegonAlpharius commented on src/store/actions/streamsAction.js
> +      NotificationManager.error(error.message, 'Post error!', 5000);
На русском нужно

2021-09-11 14:12 UTC, OmegonAlpharius commented on src/store/reducers/streamsReducer.js
> +      return { ...state, loading: true };
Одинаковый результат можно объединить в один action 
case ADD_NEW_STREAM_REQUEST:
      return { ...state, loading: true };

2021-09-11 14:12 UTC, OmegonAlpharius commented on src/store/reducers/streamsReducer.js
> +      return { ...state, error: action.error };
loading: false потерялся

2021-09-12 15:20 UTC, OmegonAlpharius approved these changes

2021-09-12 15:27 UTC, ZaurQoban commented on src/store/actions/streamsAction.js
> +      NotificationManager.error(error.response.data, 'Post error!', 5000);
@OmegonAlpharius  перевел

2021-09-12 16:16 UTC, BauyrjanSeidahmet requested changes

2021-09-12 16:16 UTC, BauyrjanSeidahmet commented on src/store/actions/streamsAction.js
Приложение падает из за того что не импортирвал NotificationManager
```suggestion
import { NotificationManager } from 'react-notifications';
```
![зау](https://user-images.githubusercontent.com/86306282/132995036-a2225894-e393-4855-8963-e44ddafd1b4d.png)

2021-09-12 17:05 UTC, ZaurQoban commented on src/store/actions/streamsAction.js
@BauyrjanSeidahmet Поправил

2021-09-12 17:19 UTC, BauyrjanSeidahmet approved these changes

2021-09-12 17:20 UTC, merged