Feature select languages
xx3u/amal_frontend pull request #60
Opened 2021-07-07 17:15 UTC by xx3u

#59 

Добавление списка для языка обучения 

Время выполнения: 15 мин

2021-07-09 13:34 UTC, OmegonAlpharius requested changes

2021-07-09 13:34 UTC, OmegonAlpharius commented on src/containers/Forms/Student/StudentForm.js
> +              {option.value}
Попробовал подставить, но все равно только value отображает
```suggestion
              {option.label}
```

2021-07-11 04:08 UTC, xx3u commented on src/containers/Forms/Student/StudentForm.js
> +              {option.value}
Исправлено

2021-07-11 12:48 UTC, BauyrjanSeidahmet approved these changes

2021-07-11 12:57 UTC, ZaurQoban approved these changes

2021-07-11 13:23 UTC, merged