Feature student ind page
xx3u/amal_frontend pull request #72
Opened 2021-07-12 11:18 UTC by ZaurQoban

Указать номер тикета
#65 
Краткое описание задачи
Создана кнопка для перехода на страницу студента, а так же - сама страница, отображающая данные по студенту, вместе с кнопкой возврата.
Выполнено: дата / Срок сдачи: дата
Затраченное время: 5 часов (в связи с необходимостью очищения памяти, просмотра видео по material-ui, неудачных попыток реализации, а так же переустановки бэка из-за сбоев).

2021-07-12 13:12 UTC, xx3u requested changes

2021-07-12 13:12 UTC, xx3u commented on src/App.js
> +          <Route path='/admin-app/students/:id' exact component={StudentContainer} />
Изменить наименование StudentContainer (типа StudentById), т.к. перекликается со StudentsContainer.

2021-07-12 13:12 UTC, xx3u commented on src/containers/StudentContainer/StudentContainer.js
> +      </Grid>
Повторяющийся блок вынести в отдельный компонент, а потом через деструктуризацию передавать данные.
```suggestion
const DataItem = ({gridClasses, labelClasses, data}) => (
      <Grid container className={gridClasses} item>
        <Typography className={labelClasses}>Имя: </Typography>
        <Typography>{data}</Typography>
      </Grid>
      );
      export default DataItem;
```

2021-07-12 13:12 UTC, xx3u commented on src/containers/StudentContainer/StudentContainer.js
> +        <Button className={classes.button} variant='contained' component={Link} to={`/admin-app/students/edit/${id}`} color='default'>
линк не работает, проверить последовательность

2021-07-12 13:12 UTC, xx3u commented on src/containers/StudentsContainer/StudentsContainer.js
> +              to={`/admin-app/students/edit/${params.row.id}`}
```suggestion
              to={`/admin-app/students/${params.row.id}`}/edit
```

2021-07-12 13:12 UTC, xx3u commented on src/containers/StudentsContainer/StudentsContainer.js
> +              to={`/admin-app/students/edit/${params.row.id}`}
в соответствие с REST

2021-07-12 16:41 UTC, xx3u commented on src/containers/StudentsContainer/StudentsContainer.js
> +              to={`/admin-app/students/edit/${params.row.id}`}
Разделить логику на Page -> отображение на странице, Container -> dispatch, передача данных, Component -> повторяющиеся блоки с деструктуризацией

2021-07-13 13:09 UTC, ZaurQoban commented on src/containers/StudentContainer/StudentContainer.js
> +      </Grid>
@xx3u Осуществил рефакторинг, но без ДатаАйтема

2021-07-13 13:10 UTC, ZaurQoban commented on src/containers/StudentContainer/StudentContainer.js
> +        <Button className={classes.button} variant='contained' component={Link} to={`/admin-app/students/edit/${id}`} color='default'>
@xx3u  Исправил

2021-07-13 13:10 UTC, ZaurQoban commented on src/containers/StudentsContainer/StudentsContainer.js
> +              to={`/admin-app/students/edit/${params.row.id}`}
@xx3u  Разделил на компоненты, контейнер и страницу

2021-07-13 18:56 UTC, xx3u commented on src/containers/StudentsContainer/StudentsContainer.js
> +              to={`/admin-app/students/${params.row.id}`}/edit
```suggestion
              to={`/admin-app/students/${params.row.id}/edit`}
```

2021-07-13 19:01 UTC, xx3u commented on src/containers/StudentDetailContainer/StudentDetailContainer.js
> +  //const id = props.match.url.split('/')[3];
Убрать закомментированный код

2021-07-13 19:01 UTC, xx3u commented on src/containers/StudentDetailContainer/StudentDetailContainer.js
> +      <StudentDetailItem label='Поток:' info={studentById.stream} />
Изменить Поток на Направление, stream на streamId
```suggestion
      <StudentDetailItem label='Направление:' info={studentById.streamId} />
```

2021-07-13 19:01 UTC, xx3u commented on src/pages/StudentDetailPage/StudentDetailPage.js
> +const useStyles = makeStyles((theme) => ({
Добавить пробел между импортом и const
```suggestion

const useStyles = makeStyles((theme) => ({
```

2021-07-14 06:45 UTC, ZaurQoban commented on src/containers/StudentDetailContainer/StudentDetailContainer.js
> +  //const id = props.match.url.split('/')[3];
@xx3u  Удален

2021-07-14 06:45 UTC, ZaurQoban commented on src/containers/StudentDetailContainer/StudentDetailContainer.js
> +      <StudentDetailItem label='Поток:' info={studentById.stream} />
@xx3u  Изменен

2021-07-14 06:46 UTC, ZaurQoban commented on src/pages/StudentDetailPage/StudentDetailPage.js
> +const useStyles = makeStyles((theme) => ({
@xx3u  Добавлен

2021-07-14 12:02 UTC, xx3u commented on src/containers/StudentDetailContainer/StudentDetailContainer.js
> +      <StudentDetailItem label='Поток:' info={studentById.streamId} />
```suggestion
      <StudentDetailItem label='Направление:' info={studentById.streamId} />
```

2021-07-14 12:05 UTC, xx3u approved these changes

2021-07-14 12:05 UTC, merged